.gitignore
build.sbt
project/BuildConfig.scala

Bumps temporal SDK, fixes #29.
Compiles and tests fine.

Bump temporal-sdk. Fixes #29.

---

core/src/main/scala/zio/temporal/ZWorkflowExecution.scala
core/src/main/scala/zio/temporal/ZWorkflowExecutionMetadata.scala
core/src/main/scala/zio/temporal/ZWorkflowInfo.scala
core/src/main/scala/zio/temporal/internal/StubProxies.scala
core/src/main/scala/zio/temporal/worker/ZWorkerFactoryOptions.scala
core/src/main/scala/zio/temporal/workflow/ZAsync.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowClient.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowClientOptions.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowServiceStubsOptions.scala
examples/src/main/scala/com/example/hello/misc/WorkflowExecutionsMain.scala

- ZAsync ops
- ZWorkflowClient.listExecutions
- Better StubProxy error
- Better config path

Enhancements leftovers

---

core/src/main/scala/zio/temporal/activity/ZActivity.scala
core/src/main/scala/zio/temporal/activity/ZActivityOptions.scala
core/src/main/scala/zio/temporal/internal/StubProxies.scala
core/src/main/scala/zio/temporal/internal/ZioUnsafeFacade.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowClient.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowStubBuilder.scala
docs/src/main/mdoc/FAQ.md
docs/src/main/mdoc/core/overview.md
examples/src/main/scala/com/example/bookingsaga/TripBookingSaga.scala
examples/src/main/scala/com/example/error/handling/exceptions.scala
examples/src/main/scala/com/example/error/handling/typed_errors.scala
integration-tests/src/test/resources/logback.xml
integration-tests/src/test/scala/zio/temporal/ActivitySpec.scala
integration-tests/src/test/scala/zio/temporal/WorkflowSpec.scala
integration-tests/src/test/scala/zio/temporal/fixture/FibonacciHeartbeatActivity.scala
project/BuildConfig.scala
testkit/src/main/scala/zio/temporal/testkit/ZTestActivityEnvironment.scala
testkit/src/main/scala/zio/temporal/testkit/ZTestWorkflowEnvironment.scala

- Fixes #61 
- Added ZTestActivityEnvironment #52 
- Better ergonomics for ZTestWorkflowEnvironment
- A few FAQ notes

Supporting local activities with ZIO; Testkit improvements

---

build.sbt
core/src/main/scala-3/zio/temporal/activity/ZActivityExecutionSyntax.scala
core/src/main/scala-3/zio/temporal/query/ZWorkflowStubQuerySyntax.scala
core/src/main/scala-3/zio/temporal/workflow/ZChildWorkflowExecutionSyntax.scala
core/src/main/scala-3/zio/temporal/workflow/ZWorkflowExecutionSyntax.scala
core/src/main/scala/zio/temporal/JavaTypeTag.scala
core/src/main/scala/zio/temporal/activity/ZActivityExecutionContext.scala
core/src/main/scala/zio/temporal/activity/ZActivityStub.scala
core/src/main/scala/zio/temporal/failure/package.scala
core/src/main/scala/zio/temporal/internal/TemporalWorkflowFacade.scala
core/src/main/scala/zio/temporal/json/JacksonDataConverter.scala
core/src/main/scala/zio/temporal/workflow/ZChildWorkflowStub.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflow.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowStub.scala
examples/src/main/scala/com/example/hello/misc/EitherWorkflowMain.scala
integration-tests/src/test/scala/zio/temporal/WorkflowComplexTypesSpec.scala
integration-tests/src/test/scala/zio/temporal/fixture/complex_type_workflow.scala
testkit/src/main/scala/zio/temporal/testkit/ZTestActivityEnvironment.scala

Introducing JavaTypeTag for better PayloadDataConverter type hinting

---

core/src/main/scala-2/zio/temporal/EnumSearchAttributes.scala
core/src/main/scala-2/zio/temporal/VersionSpecificConverters.scala
core/src/main/scala-2/zio/temporal/enumeratum/EnumSearchAttributes.scala
core/src/main/scala-2/zio/temporal/enumeratum/package.scala
core/src/main/scala-3/zio/temporal/VersionSpecificConverters.scala
core/src/main/scala/zio/temporal/ZSearchAttribute.scala
core/src/main/scala/zio/temporal/ZWorkflowInfo.scala
core/src/test/scala-2/zio/temporal/enumeratum/EnumSearchAttributesSpec.scala
examples/src/main/scala/com/example/hello/externalwf/workflows.scala

Fixing & polishing search attributes

---

protobuf/src/main/scala/zio/temporal/protobuf/internal/ProtoFileObjectAutoLoader.scala

Get rid of noisy Reflections warning

---

build.sbt
integration-tests/src/test/scala/zio/temporal/ActivitySpec.scala
integration-tests/src/test/scala/zio/temporal/WorkflowComplexTypesSpec.scala
integration-tests/src/test/scala/zio/temporal/WorkflowSpec.scala
project/BuildConfig.scala
project/scalapb.sbt

NOTE: we'll have one more RC due to 3.3.0 release 😅

Scala 3 LTS; Bump libs

---

docs/src/main/mdoc/FAQ.md
docs/src/main/mdoc/advanced/generic-workflows.md
docs/src/main/mdoc/advanced/overview.md
docs/src/main/mdoc/advanced/workflow-polymorphism.md
docs/src/main/mdoc/contribution.md
docs/src/main/mdoc/core/activities.md
docs/src/main/mdoc/core/configuration.md
docs/src/main/mdoc/core/overview.md
docs/src/main/mdoc/core/workflows.md
docs/src/main/mdoc/resilience/heartbeats.md
docs/src/main/mdoc/resilience/retries.md
docs/src/main/mdoc/resilience/sagas.md
docs/src/main/mdoc/serialization/jackson.md
docs/src/main/mdoc/serialization/overview.md
docs/src/main/mdoc/serialization/protobuf.md
docs/src/main/mdoc/testing/overview.md
docs/src/main/mdoc/testing/testing-activities.md
docs/src/main/mdoc/testing/testing-workflows.md
docs/src/main/mdoc/workflows/child-workflows.md
docs/src/main/mdoc/workflows/continue-as-new.md
docs/src/main/mdoc/workflows/external-workflows.md
docs/src/main/mdoc/workflows/queries.md
docs/src/main/mdoc/workflows/signals.md
docs/src/main/mdoc/workflows/state.md
docs/src/main/mdoc/workflows/timers.md
website/docusaurus.config.js
website/src/pages/index.js

SEO optimization for the website
Nothing

SEO optimization

---

.github/workflows/site.yaml
README.md
build.sbt

Proper readme & version in the website

---

core/src/main/scala-2.13+/zio/temporal/ZSearchAttributeMetaCollectionInstances.scala
core/src/main/scala-2.13-/zio/temporal/ZSearchAttributeMetaCollectionInstances.scala
core/src/main/scala-2/zio/temporal/ZSearchAttributeMetaEnumInstances.scala
core/src/main/scala-2/zio/temporal/ZSearchAttributeMetaVersionSpecific.scala
core/src/main/scala-2/zio/temporal/enumeratum/EnumSearchAttributes.scala
core/src/main/scala-3/zio/temporal/VersionSpecificConverters.scala
core/src/main/scala-3/zio/temporal/ZSearchAttributeMetaCollectionInstances.scala
core/src/main/scala-3/zio/temporal/ZSearchAttributeMetaEnumInstances.scala
core/src/main/scala-3/zio/temporal/ZSearchAttributeMetaVersionSpecific.scala
core/src/main/scala-3/zio/temporal/internal/Scala3EnumUtils.scala
core/src/main/scala/zio/temporal/ZCurrentTimeMillis.scala
core/src/main/scala/zio/temporal/ZSearchAttribute.scala
core/src/main/scala/zio/temporal/ZSearchAttributeMeta.scala
core/src/main/scala/zio/temporal/ZSearchAttributes.scala
core/src/main/scala/zio/temporal/ZWorkflowInfo.scala
core/src/main/scala/zio/temporal/schedules/ZScheduleOptions.scala
core/src/main/scala/zio/temporal/workflow/ZChildWorkflowStubBuilder.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflow.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowStubBuilder.scala
core/src/test/scala-2/zio/temporal/enumeratum/EnumSearchAttributesSpec.scala
core/src/test/scala-3/zio/temporal/EnumSearchAttributesSpec.scala
core/src/test/scala/zio/temporal/ZSearchAttributeMetaSpec.scala
core/src/test/scala/zio/temporal/ZSearchAttributesSpec.scala
examples/src/main/scala/com/example/externalwf/Main.scala
examples/src/main/scala/com/example/externalwf/workflows.scala
project/BuildConfig.scala
protobuf/src/main/scala-3/zio/temporal/protobuf/EnumProtoType.scala

Migrating to typed search attributes.
Resolved #99 
Using raw types was deprecated recently in Java SDK

Migrating to typed search attributes

---

.github/workflows/site.yaml
website/docusaurus.config.js

Site: Remove trailing slash

---

.github/workflows/ci.yaml
core/src/main/scala/zio/temporal/schedules/ZSchedule.scala
docs/src/main/mdoc/workflows/child-workflows.md
docs/src/main/mdoc/workflows/external-workflows.md
docs/src/main/mdoc/workflows/schedules.md
docs/src/main/mdoc/workflows/versioning.md
examples/src/main/scala/com/example/schedule/ScheduledWorkflowMain.scala
website/docusaurus.config.js
website/sidebars.js

- Allow updating schedule action
- Schedules documentation
- Versioning doc

Documentation for 0.3.0

---

Makefile
core/src/main/scala-2.13+/zio/temporal/ZSearchAttributeMetaCollectionInstances.scala
core/src/main/scala-2.13-/zio/temporal/ZSearchAttributeMetaCollectionInstances.scala
core/src/main/scala-3/zio/temporal/ZSearchAttributeMetaCollectionInstances.scala
core/src/main/scala/zio/temporal/ZSearchAttributeMeta.scala
core/src/main/scala/zio/temporal/package.scala
core/src/main/scala/zio/temporal/workflow/ZWorkflowServiceStubsOptions.scala
core/src/test/scala-2/zio/temporal/enumeratum/EnumSearchAttributesSpec.scala
docs/src/main/mdoc/observability.md
examples/src/main/scala/com/example/monitoring/MonitoringMain.scala
examples/src/main/scala/com/example/monitoring/README.md
examples/src/main/scala/com/example/monitoring/workflows.scala
project/BuildConfig.scala
website/sidebars.js

Observability examples & doc

---

project/BuildConfig.scala

Bump zio to 2.0.16

---

build.sbt

Fix site version

---

website/src/pages/index.js

Fix typo in index.js

---

website/src/pages/index.js

Website: make key messages sound better

---

core/src/main/scala/zio/temporal/workflow/ZWorkflow.scala
integration-tests/src/test/scala/zio/temporal/WorkflowSpec.scala
integration-tests/src/test/scala/zio/temporal/fixture/RetryWorkflow.scala

Add `Workflow.retry` method with a simple integration test.

Add Workflow.retry method

---

.github/workflows/ci.yaml
core/src/main/scala/zio/temporal/workflow/ZWorkflow.scala

Minor formatting stuff; added ZWorkflow.metriscScope

---

integration-tests/src/main/protobuf/protobuf-tests.proto
integration-tests/src/test/scala/zio/temporal/protobuf/ScalapbPayloadConverterSpec.scala
integration-tests/src/test/scala/zio/temporal/protobuf/internal/ProtoFileObjectAutoLoaderSpec.scala
protobuf/src/main/scala/zio/temporal/protobuf/ScalapbPayloadConverter.scala

Added protobuf payload converter tests. They should simplify work on #117

Added protobuf payload converter tests

---

docs/src/main/mdoc/serialization/protobuf.md

Fix protobuf doc

---

core/src/main/scala/zio/temporal/worker/ZWorker.scala
integration-tests/src/test/scala/zio/temporal/WorkerSpec.scala

Added ZWorker.addActivityImplementationLayer method. It allows adding a single activity as a ZLayer

Added ZWorker.addActivityImplementationLayer method

---

website/src/pages/index.js

Home page: use the new options syntax

---

docs/src/main/mdoc/FAQ.md
docs/src/main/mdoc/resilience/retries.md

Minor documentation fixes

---

docs/src/main/mdoc/observability.md
project/BuildConfig.scala
project/build.properties

Fix site and bump more stuff

---

core/src/main/scala/zio/temporal/internal/StubProxies.scala

Use Thread getContextClassLoader when creating stubs
